---
title: "Logan's Trajectory Plots"
author: "Delphi State Hospitalizations, Forecast on:"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
params:
  data_path: "covid/results-2022-01-16.RDS"
---

```{r setup, include=FALSE, echo=FALSE}
library(evalcast)
library(zookeeper)
library(lubridate)
library(tidyverse)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message=FALSE)
source(here::here("other-code", "hosp_production_params.R"))
corrections_lookback <- 365
s3b <- aws.s3::get_bucket("forecasting-team-data")
antelope  <- aws.s3::s3readRDS(params$data_path, s3b)
antelope <- antelope$predictions.cards.subset %>%
  dplyr::filter(forecaster %in% c("dev6v3", "dev6v3_logistic1jf_marginal_usdl", "dev8v3")) 
```
	
## Trajectory plots {.tabset}


### dev6v3

```{r, fig.height = 80, fig.width = 30, dev="CairoSVG", eval=TRUE}
g <- plot_trajectory(antelope %>% dplyr::filter(forecaster == "dev6v3"),
                "state", start_day = "2021-11-15", plot_it = FALSE)
g + theme_bw(base_size = 30) + 
  facet_wrap(~geo_value, ncol = 5, scales = "free_y") +
  scale_color_manual(values = "orange") +
  scale_fill_brewer(palette = "Blues") +
  theme(legend.position = "none") 
```

### dev8v3

```{r, fig.height = 80, fig.width = 30, dev="CairoSVG", eval=TRUE}
g <- plot_trajectory(antelope %>% dplyr::filter(forecaster == "dev8v3"),
                "state", start_day = "2021-11-15", ncol = 5, plot_it = FALSE)
g + theme_bw(base_size = 30) + 
  facet_wrap(~geo_value, ncol = 5, scales = "free_y") +
  scale_color_manual(values = "orange") +
  scale_fill_brewer(palette = "Blues") +
  theme(legend.position = "none")
```

### dev6v3_logistic1jf_marginal_usdl

```{r, fig.height = 80, fig.width = 30, dev="CairoSVG", eval=TRUE}
g <- plot_trajectory(
  antelope %>% dplyr::filter(forecaster == "dev6v3_logistic1jf_marginal_usdl"),
  "state", start_day = "2021-11-15", ncol = 5, plot_it = FALSE)
g + theme_bw(base_size = 30) + 
  facet_wrap(~geo_value, ncol = 5, scales = "free_y") +
  scale_color_manual(values = "orange") +
  scale_fill_brewer(palette = "Blues") +
  theme(legend.position = "none")
```



## Compare to hub

* We grab two hub forecasts, the ensemble and UMASS trends


```{r, fig.height = 80, fig.width = 30, dev="CairoSVG", echo=FALSE}
hub <- get_covidhub_predictions(
  c("COVIDhub-4_week_ensemble", "UMass-trends_ensemble"),
  forecast_dates = "2022-01-10", forecast_type = "point", 
  ahead = 0:28, incidence_period = "day", signal = "confirmed_admissions_covid_1d")
antelope <- antelope %>%
  dplyr::filter(abs(quantile - .5) < 1e-3) %>%
  mutate(quantile = NA)
hub_and_ours <- bind_rows(hub, antelope %>% filter(is.na(quantile)))
actuals <- covidcast::covidcast_signal("hhs", "confirmed_admissions_covid_1d",
                                       start_day = "2021-12-01", geo_type = "state")
ggplot(hub_and_ours) +
  geom_line(aes(target_end_date, value, color = forecaster)) +
  geom_point(aes(target_end_date, value, color = forecaster), size=3) +
  geom_line(data = actuals, aes(time_value, value), color = "black") +
  geom_point(data = actuals, aes(time_value, value), color = "black", size=3) +
  scale_color_brewer(palette = "Set1") +
  facet_wrap(~geo_value, scales = "free_y", ncol=5) + 
  theme_bw(base_size = 30) +
  theme(legend.position = "bottom")

```
